/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */

#ifndef E2AP_NODE_COMP_INTERFACE_TYPE_MIR_H
#define E2AP_NODE_COMP_INTERFACE_TYPE_MIR_H

// 9.2.26
typedef enum{
  NG_E2AP_NODE_COMP_INTERFACE_TYPE = 0, 
  XN_E2AP_NODE_COMP_INTERFACE_TYPE = 1, 
  E1_E2AP_NODE_COMP_INTERFACE_TYPE = 2,
  F1_E2AP_NODE_COMP_INTERFACE_TYPE = 3, 
  W1_E2AP_NODE_COMP_INTERFACE_TYPE = 4, 
  S1_E2AP_NODE_COMP_INTERFACE_TYPE = 5, 
  X2_E2AP_NODE_COMP_INTERFACE_TYPE = 6,

  END_E2AP_NODE_COMP_INTERFACE_TYPE
} e2ap_node_comp_interface_type_e;

#endif
