/*
 * SPDX-License-Identifier: LicenseRef-CSSL-1.0
 */



#ifndef SM_ALLOCATION_H
#define SM_ALLOCATION_H

////////////////////////////////////
// 5 ORAN E2AP procedures 
// defined in ORAN-WG3.E2SM-v01.00.00  
///////////////////////////////////

// (De)Allocation of the messages generated by the Service Models


#include <stddef.h> 
#include <stdint.h>

typedef struct{

  void (*free_subs_data_msg)(void* msg);

  void (*free_ind_data)(void* msg);

  void (*free_ctrl_out_data)(void* msg);

  void (*free_ctrl_req_data)(void* msg);

  void (*free_e2_setup)(void* msg);

  void (*free_ric_service_update)(void* msg);

} sm_alloc_t;

#endif

