# SPDX-License-Identifier: MIT
# ---------------------------------------------------------------------
#
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "flexric-build-cfg"
spec:
    runPolicy: "Serial"
    source:
        type: "Binary"
        secrets:
          - secret:
              name: etc-pki-entitlement
            destinationDir: etc-pki-entitlement
    strategy:
        dockerStrategy:
            dockerfilePath: "docker/Dockerfile.flexric.rhel"
    output:
        to:
            kind: "ImageStreamTag"
            name: "oai-flexric:latest"
